Hw08 envdir tool
DrBlizzzz/homeworks pull request #7
Opened 2023-04-02 08:35 UTC by DrBlizzzz

## Домашнее задание №8 «Утилита envdir»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я провел ручное тестирование программы (например, запускал `test.sh`).

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2023-04-10 08:17 UTC, dshemin requested changes

2023-04-10 08:17 UTC, dshemin commented on hw08_envdir_tool/env_reader.go
> +		buffer, err := os.ReadFile(path.Join(dir, entryName))
Критично:

Согласно заданию, мы должны игнорировать файлы, в названии которых есть `=`.

2023-04-10 08:17 UTC, dshemin commented on hw08_envdir_tool/executor.go
> +		os.Setenv(k, v.Value)
Критично:

Нет проверки на значение `NeedRemove`. Если оно выставлено в true, то мы должны удалить переменную окружения.

2023-05-20 08:39 UTC, DrBlizzzz commented on hw08_envdir_tool/env_reader.go
> +		buffer, err := os.ReadFile(path.Join(dir, entryName))
Исправлено

2023-05-20 08:39 UTC, DrBlizzzz commented on hw08_envdir_tool/executor.go
> +		os.Setenv(k, v.Value)
Исправлено

2023-05-21 18:57 UTC, dshemin requested changes

2023-05-21 18:57 UTC, dshemin commented on hw08_envdir_tool/env_reader.go
> +		if ind := strings.Index(entryName, "="); ind >= 0 {
Важно:

https://pkg.go.dev/strings#ContainsRune

2023-05-21 18:57 UTC, dshemin commented on hw08_envdir_tool/main.go
> +	env, _ := ReadDir(os.Args[1])
Важно:

Игнорирование ошибки, так быть не должно.

2023-05-21 18:57 UTC, dshemin commented on hw08_envdir_tool/main.go
> +	_ = RunCmd(os.Args[2:], env)
Критично:

>  код выхода утилиты совпадал с кодом выхода программы.

Не соответствует критерии.

2023-07-24 19:10 UTC, merged